---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather-alerts.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "weather-alerts.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "weather-alerts.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather-alerts.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "weather-alerts.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "weather-alerts.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
