{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "weather-alerts.fullname" . }}-ingress"
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
  - host: "{{ .host }}"
    http:
      paths:
{{- range .paths }}
      - path: "{{ . }}"
        pathType: Prefix
        backend:
          service:
            name: "{{ include "weather-alerts.fullname" $. }}"
            port:
              number: {{ $.Values.service.frontendPort }}
{{- end }}
{{- end }}
{{- end }}
