version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-cli: circleci/aws-cli@4.0.0
  terraform: circleci/terraform@1.0.5
  helm: circleci/helm@0.4.0

jobs:
  lint:
    executor:
      name: cimg/base:stable
      working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Terraform FMT Check
          command: cd terraform && terraform fmt -check
      - run:
          name: Run TFLint
          command: cd terraform && tflint --init && tflint --config .tflint.hcl
      - run:
          name: Run Checkov
          command: cd terraform && checkov -d .
      - run:
          name: Run yamllint
          command: |
            if [ -f .yamllint.yml ]; then
              yamllint .
            else
              echo "No .yamllint.yml file; skipping yamllint."
            fi

  plan:
    executor:
      name: cimg/base:stable
      working_directory: ~/project/terraform
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
          extra_args: ["-out=tfplan"]
      - run:
          name: Show Terraform Plan
          command: terraform show -no-color tfplan > plan-output.txt
      - run:
          name: Authenticate GitHub CLI
          command: echo "$GITHUB_TOKEN" | gh auth login --with-token
      - run:
          name: Post Terraform Plan to PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              gh pr comment --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --body "$(cat plan-output.txt)"
            else
              echo "Not a PR build; skipping PR comment."
            fi

  build:
    executor:
      name: cimg/docker:stable
      working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/login:
          aws-region: << parameters.aws_region >>  # Alternatively, you can hardcode "us-east-1" if desired
          account-url: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - run:
          name: Build Backend Image
          command: |
            cd backend
            docker build -t weather-alerts-backend -f Dockerfile .
            cd ..
      - run:
          name: Tag and Push Backend Image to ECR
          command: |
            docker tag weather-alerts-backend $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-backend:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-backend:latest
      - run:
          name: Build Frontend Image
          command: |
            cd frontend
            docker build -t weather-alerts-frontend -f Dockerfile .
            cd ..
      - run:
          name: Tag and Push Frontend Image to ECR
          command: |
            docker tag weather-alerts-frontend $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-frontend:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-frontend:latest

  deploy:
    executor:
      name: cimg/base:stable
      working_directory: ~/project/terraform
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/apply:
          path: .
          auto-approve: true
      - helm/install:
          chart: ../helm
          release: weather-alerts
          set:
            backend.image: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-backend"
            frontend.image: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/weather-alerts-frontend"

  monitoring:
    executor:
      name: cimg/base:stable
      working_directory: ~/project/terraform
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/apply:
          path: .
          auto-approve: true
          targets:
            - kubernetes_namespace.monitoring
            - helm_release.prometheus
            - helm_release.grafana

workflows:
  version: 2
  deploy:
    jobs:
      - lint
      - plan
      - build
      - deploy
      - monitoring
