backend:
  image: "REPLACE_WITH_IMAGE"   # This will be overridden by deploy.sh or CI/CD.
  pullPolicy: Always
  port: 8000

frontend:
  image: "REPLACE_WITH_IMAGE"   # This will be overridden by deploy.sh or CI/CD.
  pullPolicy: Always
  port: 80

service:
  type: ClusterIP
  backendPort: 8000
  frontendPort: 80

ingress:
  enabled: true
  hosts:
    - host: weather-alerts.example.com
      paths:
        - /
  annotations: 
    kubernetes.io/ingress.class: alb  # If using AWS ALB Ingress Controller